#!/usr/bin/env bash
# Paqet X server installer, using the upstream open-source hanselime/paqet core.
#
# Official repository for this installer:
#   https://github.com/Unknown-sir/paqetX
#
# One-command install:
#   curl -fsSL https://raw.githubusercontent.com/Unknown-sir/paqetX/main/paqet-x-install.sh | sudo bash
#
# Optional arguments:
#   --port PORT             Server port (default: 9999 on first install)
#   --version TAG           Release tag, or "latest"
#   --interface NAME        Override detected network interface
#   --local-ip IPV4         Override detected local IPv4 address
#   --router-mac MAC        Override detected gateway MAC address
#   --key KEY               Set a shared key (auto-generated by default)
#   --force-config          Back up and replace an existing configuration
#   --no-start              Install files but do not start services
#   --help                  Show help
#
# Equivalent environment variables:
#   PAQET_PORT, PAQET_VERSION, PAQET_INTERFACE, PAQET_LOCAL_IP,
#   PAQET_ROUTER_MAC, PAQET_KEY, FORCE_CONFIG=1, SKIP_START=1,
#   GITHUB_TOKEN (optional; avoids anonymous API rate limits), NO_COLOR=1.

set -Eeuo pipefail
IFS=$'\n\t'
umask 077

readonly INSTALLER_NAME="Paqet X Server Installer"
readonly INSTALLER_REPOSITORY="Unknown-sir/paqetX"
readonly REPOSITORY="hanselime/paqet"
readonly API_BASE="https://api.github.com/repos/${REPOSITORY}"
readonly BIN_PATH="/usr/local/bin/paqet"
readonly CONFIG_DIR="/etc/paqet-x"
readonly CONFIG_PATH="${CONFIG_DIR}/server.yaml"
readonly FIREWALL_ENV="${CONFIG_DIR}/firewall.env"
readonly LIB_DIR="/usr/local/lib/paqet-x"
readonly FIREWALL_SCRIPT="${LIB_DIR}/firewall.sh"
readonly STATE_DIR="/var/lib/paqet-x"
readonly VERSION_FILE="${STATE_DIR}/version"
readonly SERVICE_NAME="paqet-x.service"
readonly FIREWALL_SERVICE_NAME="paqet-x-firewall.service"
readonly SERVICE_PATH="/etc/systemd/system/${SERVICE_NAME}"
readonly FIREWALL_SERVICE_PATH="/etc/systemd/system/${FIREWALL_SERVICE_NAME}"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  readonly RED=$'\033[0;31m'
  readonly GREEN=$'\033[0;32m'
  readonly YELLOW=$'\033[1;33m'
  readonly BLUE=$'\033[0;34m'
  readonly BOLD=$'\033[1m'
  readonly RESET=$'\033[0m'
else
  readonly RED="" GREEN="" YELLOW="" BLUE="" BOLD="" RESET=""
fi

CURRENT_STEP="initialization"
TMP_DIR=""
STEP_NUMBER=0
TOTAL_STEPS=9

log_info()    { printf '%s[INFO]%s %s\n' "$BLUE" "$RESET" "$*"; }
log_success() { printf '%s[ OK ]%s %s\n' "$GREEN" "$RESET" "$*"; }
log_warn()    { printf '%s[WARN]%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
log_error()   { printf '%s[FAIL]%s %s\n' "$RED" "$RESET" "$*" >&2; }
die()         { log_error "$*"; exit 1; }

step() {
  STEP_NUMBER=$((STEP_NUMBER + 1))
  CURRENT_STEP="$*"
  printf '\n%s[%d/%d]%s %s%s%s\n' "$BLUE" "$STEP_NUMBER" "$TOTAL_STEPS" "$RESET" "$BOLD" "$*" "$RESET"
}

cleanup() {
  if [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]]; then
    rm -rf -- "$TMP_DIR"
  fi
}

on_error() {
  local exit_code=$?
  local line_no="${BASH_LINENO[0]:-unknown}"
  local command_text="${BASH_COMMAND:-unknown}"
  log_error "Installation stopped during: ${CURRENT_STEP}"
  log_error "Line ${line_no}: ${command_text} (exit ${exit_code})"
  exit "$exit_code"
}

trap cleanup EXIT
trap on_error ERR

usage() {
  cat <<'USAGE'
Paqet X server installer (upstream hanselime/paqet core)

Usage:
  sudo bash paqet-x-install.sh [options]
  curl -fsSL https://raw.githubusercontent.com/Unknown-sir/paqetX/main/paqet-x-install.sh | sudo bash -s -- [options]

Options:
  --port PORT             Server port, 1024-65535; not 80 or 443
  --version TAG           Release tag such as v1.0.0-alpha.20, or latest
  --interface NAME        Network interface override
  --local-ip IPV4         Local IPv4 override
  --router-mac MAC        Gateway/router MAC override
  --key KEY               Shared key (16-128 safe characters)
  --force-config          Replace existing config after making a backup
  --no-start              Do not enable or start the services
  -h, --help              Show this help

Rerun behavior:
  Existing configuration is preserved unless --force-config is used.
  Existing installs stay on their recorded version unless --version is supplied.
USAGE
}

PAQET_PORT="${PAQET_PORT:-9999}"
PAQET_VERSION_REQUEST="${PAQET_VERSION:-}"
PAQET_INTERFACE="${PAQET_INTERFACE:-}"
PAQET_LOCAL_IP="${PAQET_LOCAL_IP:-}"
PAQET_ROUTER_MAC="${PAQET_ROUTER_MAC:-}"
PAQET_KEY="${PAQET_KEY:-}"
FORCE_CONFIG="${FORCE_CONFIG:-0}"
SKIP_START="${SKIP_START:-0}"

while (($# > 0)); do
  case "$1" in
    --port)
      (($# >= 2)) || die "--port requires a value"
      PAQET_PORT="$2"
      shift 2
      ;;
    --version)
      (($# >= 2)) || die "--version requires a value"
      PAQET_VERSION_REQUEST="$2"
      shift 2
      ;;
    --interface)
      (($# >= 2)) || die "--interface requires a value"
      PAQET_INTERFACE="$2"
      shift 2
      ;;
    --local-ip)
      (($# >= 2)) || die "--local-ip requires a value"
      PAQET_LOCAL_IP="$2"
      shift 2
      ;;
    --router-mac)
      (($# >= 2)) || die "--router-mac requires a value"
      PAQET_ROUTER_MAC="$2"
      shift 2
      ;;
    --key)
      (($# >= 2)) || die "--key requires a value"
      PAQET_KEY="$2"
      shift 2
      ;;
    --force-config)
      FORCE_CONFIG=1
      shift
      ;;
    --no-start)
      SKIP_START=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1 (use --help)"
      ;;
  esac
done

validate_boolean() {
  local name="$1" value="$2"
  [[ "$value" == "0" || "$value" == "1" ]] || die "${name} must be 0 or 1"
}

validate_port() {
  local port="$1"
  [[ "$port" =~ ^[0-9]+$ ]] || die "Invalid port: ${port}"
  [[ "$port" != "80" && "$port" != "443" ]] || die "Do not use port 80 or 443 with Paqet firewall rules"
  ((port >= 1024 && port <= 65535)) || die "Port must be between 1024 and 65535"
}

validate_ipv4() {
  local ip="$1" part
  local -a octets
  IFS='.' read -r -a octets <<<"$ip"
  ((${#octets[@]} == 4)) || return 1
  for part in "${octets[@]}"; do
    [[ "$part" =~ ^[0-9]{1,3}$ ]] || return 1
    ((10#$part >= 0 && 10#$part <= 255)) || return 1
  done
}

validate_interface() {
  [[ "$1" =~ ^[A-Za-z0-9_.:@-]+$ ]]
}

validate_mac() {
  [[ "$1" =~ ^([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}$ ]]
}

validate_key() {
  [[ "$1" =~ ^[A-Za-z0-9._~-]{16,128}$ ]]
}

validate_release_tag() {
  [[ "$1" == "latest" || "$1" =~ ^v?[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]]
}

validate_boolean "FORCE_CONFIG" "$FORCE_CONFIG"
validate_boolean "SKIP_START" "$SKIP_START"
validate_port "$PAQET_PORT"
[[ -z "$PAQET_VERSION_REQUEST" ]] || validate_release_tag "$PAQET_VERSION_REQUEST" || die "Invalid release tag: ${PAQET_VERSION_REQUEST}"
[[ -z "$PAQET_INTERFACE" ]] || validate_interface "$PAQET_INTERFACE" || die "Invalid interface name: ${PAQET_INTERFACE}"
[[ -z "$PAQET_LOCAL_IP" ]] || validate_ipv4 "$PAQET_LOCAL_IP" || die "Invalid IPv4 address: ${PAQET_LOCAL_IP}"
[[ -z "$PAQET_ROUTER_MAC" ]] || validate_mac "$PAQET_ROUTER_MAC" || die "Invalid router MAC: ${PAQET_ROUTER_MAC}"
[[ -z "$PAQET_KEY" ]] || validate_key "$PAQET_KEY" || die "Key must be 16-128 characters using letters, numbers, dot, underscore, tilde, or hyphen"

printf '%s%s%s\n' "$BOLD" "$INSTALLER_NAME" "$RESET"
printf 'Installer: https://github.com/%s\n' "$INSTALLER_REPOSITORY"
printf 'Upstream:  https://github.com/%s\n' "$REPOSITORY"

step "Checking privileges and platform"

if ((EUID != 0)); then
  die "Root privileges are required. Run: sudo bash paqet-x-install.sh"
fi

[[ "$(uname -s)" == "Linux" ]] || die "This installer supports Linux only"

if [[ ! -d /run/systemd/system ]]; then
  die "systemd is required and does not appear to be the active init system"
fi

case "$(uname -m)" in
  x86_64|amd64)
    PAQET_ARCH="amd64"
    ARCH_BINARY_NAME="paqet_linux_amd64"
    ;;
  aarch64|arm64)
    PAQET_ARCH="arm64"
    ARCH_BINARY_NAME="paqet_linux_arm64"
    ;;
  armv7l|armv7)
    PAQET_ARCH="arm32"
    ARCH_BINARY_NAME="paqet_linux_arm32"
    ;;
  *)
    die "Unsupported CPU architecture: $(uname -m). Supported: x86_64, arm64, armv7"
    ;;
esac

log_success "Linux $(uname -m), systemd, root access"

step "Installing required system packages"

install_dependencies() {
  local -a required_commands=(curl jq tar ip iptables systemctl sha256sum install awk sed grep find)
  local -a missing=()
  local cmd

  for cmd in "${required_commands[@]}"; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done

  if ((${#missing[@]} == 0)); then
    log_success "Required commands are already installed"
    return 0
  fi

  log_info "Missing commands: ${missing[*]}"

  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y --no-install-recommends ca-certificates curl jq tar iproute2 iptables iputils-ping
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y ca-certificates curl jq tar iproute iputils
    if ! dnf install -y iptables; then
      dnf install -y iptables-nft
    fi
  elif command -v yum >/dev/null 2>&1; then
    yum install -y ca-certificates curl jq tar iproute iputils
    if ! yum install -y iptables; then
      yum install -y iptables-nft
    fi
  elif command -v pacman >/dev/null 2>&1; then
    pacman -Sy --noconfirm --needed ca-certificates curl jq tar iproute2 iptables iputils
  elif command -v zypper >/dev/null 2>&1; then
    zypper --non-interactive install ca-certificates curl jq tar iproute2 iptables iputils
  else
    die "No supported package manager found. Install curl, jq, tar, iproute2, iptables, and ca-certificates, then rerun"
  fi

  for cmd in "${required_commands[@]}"; do
    command -v "$cmd" >/dev/null 2>&1 || die "Required command is still missing after package installation: $cmd"
  done

  log_success "System packages installed"
}

install_dependencies

step "Resolving the Paqet release"

if [[ -z "$PAQET_VERSION_REQUEST" ]]; then
  if [[ -s "$VERSION_FILE" && -x "$BIN_PATH" ]]; then
    PAQET_VERSION_REQUEST="$(tr -d '[:space:]' < "$VERSION_FILE")"
    validate_release_tag "$PAQET_VERSION_REQUEST" || die "Recorded version is invalid: ${PAQET_VERSION_REQUEST}"
    log_info "Existing install detected; keeping recorded version ${PAQET_VERSION_REQUEST}"
  else
    PAQET_VERSION_REQUEST="latest"
  fi
fi

if [[ "$PAQET_VERSION_REQUEST" == "latest" ]]; then
  RELEASE_API_URL="${API_BASE}/releases/latest"
else
  RELEASE_API_URL="${API_BASE}/releases/tags/${PAQET_VERSION_REQUEST}"
fi

CURL_HEADERS=(
  -H "Accept: application/vnd.github+json"
  -H "X-GitHub-Api-Version: 2026-03-10"
  -H "User-Agent: paqet-x-installer"
)
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  CURL_HEADERS+=( -H "Authorization: Bearer ${GITHUB_TOKEN}" )
fi

TMP_DIR="$(mktemp -d -t paqet-x-install.XXXXXXXX)"
RELEASE_JSON="${TMP_DIR}/release.json"

curl --proto '=https' --tlsv1.2 -fsSL \
  --retry 3 --retry-delay 2 --connect-timeout 10 --max-time 60 \
  "${CURL_HEADERS[@]}" "$RELEASE_API_URL" -o "$RELEASE_JSON"

RELEASE_TAG="$(jq -er '.tag_name' "$RELEASE_JSON")"
validate_release_tag "$RELEASE_TAG" || die "GitHub returned an invalid release tag: ${RELEASE_TAG}"

ASSET_NAME="paqet-linux-${PAQET_ARCH}-${RELEASE_TAG}.tar.gz"
ASSET_URL="$(jq -er --arg name "$ASSET_NAME" '.assets[] | select(.name == $name) | .browser_download_url' "$RELEASE_JSON")"
ASSET_DIGEST="$(jq -er --arg name "$ASSET_NAME" '.assets[] | select(.name == $name) | .digest // empty' "$RELEASE_JSON")"

[[ "$ASSET_URL" == "https://github.com/${REPOSITORY}/releases/download/"* ]] || die "Unexpected release asset URL: ${ASSET_URL}"
[[ "$ASSET_DIGEST" =~ ^sha256:[[:xdigit:]]{64}$ ]] || die "The release does not provide a valid SHA-256 digest for ${ASSET_NAME}"

EXPECTED_SHA256="${ASSET_DIGEST#sha256:}"
EXPECTED_SHA256="${EXPECTED_SHA256,,}"
log_success "Resolved ${RELEASE_TAG} for linux/${PAQET_ARCH}"

step "Downloading and verifying the release"

ARCHIVE_PATH="${TMP_DIR}/${ASSET_NAME}"
EXTRACT_DIR="${TMP_DIR}/extract"
mkdir -p "$EXTRACT_DIR"

curl --proto '=https' --tlsv1.2 -fL \
  --retry 3 --retry-delay 2 --connect-timeout 10 --max-time 300 \
  "$ASSET_URL" -o "$ARCHIVE_PATH"

[[ -s "$ARCHIVE_PATH" ]] || die "Downloaded archive is empty"
ACTUAL_SHA256="$(sha256sum "$ARCHIVE_PATH" | awk '{print $1}')"
[[ "$ACTUAL_SHA256" == "$EXPECTED_SHA256" ]] || die "SHA-256 verification failed for ${ASSET_NAME}"

TAR_LIST="${TMP_DIR}/archive.list"
tar -tzf "$ARCHIVE_PATH" > "$TAR_LIST"
while IFS= read -r archive_entry; do
  [[ "$archive_entry" != /* ]] || die "Unsafe absolute path in release archive: ${archive_entry}"
  case "/${archive_entry}/" in
    *"/../"*) die "Unsafe parent-directory path in release archive: ${archive_entry}" ;;
  esac
done < "$TAR_LIST"

while IFS= read -r archive_listing; do
  archive_type="${archive_listing:0:1}"
  [[ "$archive_type" == "-" || "$archive_type" == "d" ]] || \
    die "Unsafe non-regular entry in release archive (type ${archive_type})"
done < <(tar -tvzf "$ARCHIVE_PATH")

tar -xzf "$ARCHIVE_PATH" -C "$EXTRACT_DIR" --no-same-owner --no-same-permissions

mapfile -t BINARY_MATCHES < <(find "$EXTRACT_DIR" -type f -name "$ARCH_BINARY_NAME" -print)
((${#BINARY_MATCHES[@]} == 1)) || die "Expected one ${ARCH_BINARY_NAME} binary, found ${#BINARY_MATCHES[@]}"
DOWNLOADED_BINARY="${BINARY_MATCHES[0]}"
chmod 0755 "$DOWNLOADED_BINARY"

VERSION_OUTPUT="$($DOWNLOADED_BINARY version 2>&1)" || die "Downloaded binary failed its version check"
log_info "Binary reports: ${VERSION_OUTPUT//$'\n'/ }"
log_success "Release digest and binary check passed"

step "Installing the Paqet binary atomically"

install -d -m 0755 "$(dirname "$BIN_PATH")" "$STATE_DIR"
NEW_BIN="${BIN_PATH}.new.$$"
install -m 0755 -o root -g root "$DOWNLOADED_BINARY" "$NEW_BIN"
mv -f "$NEW_BIN" "$BIN_PATH"
printf '%s\n' "$RELEASE_TAG" > "$VERSION_FILE"
chmod 0644 "$VERSION_FILE"
log_success "Installed ${BIN_PATH} (${RELEASE_TAG})"

extract_config_port() {
  local path="$1"
  awk '
    /^[[:space:]]+addr:[[:space:]]*":[0-9]+"/ {
      value = $0
      sub(/^.*:/, "", value)
      sub(/".*$/, "", value)
      print value
      exit
    }' "$path"
}

extract_config_key() {
  local path="$1"
  awk '
    /^[[:space:]]+key:[[:space:]]*"[^"]+"/ {
      value = $0
      sub(/^[^"]*"/, "", value)
      sub(/".*$/, "", value)
      key = value
    }
    END { if (key != "") print key }' "$path"
}

extract_config_interface() {
  local path="$1"
  awk '
    /^[[:space:]]+interface:[[:space:]]*"[^"]+"/ {
      value = $0
      sub(/^[^"]*"/, "", value)
      sub(/".*$/, "", value)
      print value
      exit
    }' "$path"
}

extract_config_local_ip() {
  local path="$1"
  awk '
    /^[[:space:]]+addr:[[:space:]]*"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+"/ {
      value = $0
      sub(/^[^"]*"/, "", value)
      sub(/:[0-9]+".*$/, "", value)
      print value
      exit
    }' "$path"
}

extract_config_router_mac() {
  local path="$1"
  awk '
    /^[[:space:]]+router_mac:[[:space:]]*"[^"]+"/ {
      value = $0
      sub(/^[^"]*"/, "", value)
      sub(/".*$/, "", value)
      print value
      exit
    }' "$path"
}

PRESERVE_EXISTING_CONFIG=0
if [[ -f "$CONFIG_PATH" && "$FORCE_CONFIG" != "1" ]]; then
  PRESERVE_EXISTING_CONFIG=1
fi

step "Detecting server network settings"

get_default_interface() {
  ip -4 route show default 2>/dev/null | awk '
    NR == 1 {
      for (i = 1; i <= NF; i++) {
        if ($i == "dev" && (i + 1) <= NF) { print $(i + 1); exit }
      }
    }'
}

get_local_ip() {
  local interface="$1" result
  result="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '
    NR == 1 {
      for (i = 1; i <= NF; i++) {
        if ($i == "src" && (i + 1) <= NF) { print $(i + 1); exit }
      }
    }' || true)"
  if [[ -z "$result" ]]; then
    result="$(ip -4 -o addr show dev "$interface" scope global 2>/dev/null | awk 'NR == 1 { split($4, a, "/"); print a[1] }' || true)"
  fi
  printf '%s' "$result"
}

get_gateway_ip() {
  local interface="$1"
  ip -4 route show default dev "$interface" 2>/dev/null | awk '
    NR == 1 {
      for (i = 1; i <= NF; i++) {
        if ($i == "via" && (i + 1) <= NF) { print $(i + 1); exit }
      }
    }'
}

get_neighbor_mac() {
  local interface="$1" gateway="$2"
  ip neigh show to "$gateway" dev "$interface" 2>/dev/null | awk '
    NR == 1 {
      for (i = 1; i <= NF; i++) {
        if ($i == "lladdr" && (i + 1) <= NF) { print $(i + 1); exit }
      }
    }'
}

if [[ "$PRESERVE_EXISTING_CONFIG" == "1" ]]; then
  PAQET_INTERFACE="$(extract_config_interface "$CONFIG_PATH")"
  PAQET_LOCAL_IP="$(extract_config_local_ip "$CONFIG_PATH")"
  PAQET_ROUTER_MAC="$(extract_config_router_mac "$CONFIG_PATH")"
  log_info "Existing configuration detected; network auto-detection is not needed"
else
  if [[ -z "$PAQET_INTERFACE" ]]; then
    PAQET_INTERFACE="$(get_default_interface || true)"
  fi
  [[ -n "$PAQET_INTERFACE" ]] || die "Could not detect a default IPv4 interface. Rerun with --interface NAME"
  validate_interface "$PAQET_INTERFACE" || die "Detected an invalid interface name: ${PAQET_INTERFACE}"
  ip link show dev "$PAQET_INTERFACE" >/dev/null 2>&1 || die "Network interface does not exist: ${PAQET_INTERFACE}"

  if [[ -z "$PAQET_LOCAL_IP" ]]; then
    PAQET_LOCAL_IP="$(get_local_ip "$PAQET_INTERFACE" || true)"
  fi
  validate_ipv4 "$PAQET_LOCAL_IP" || die "Could not detect a valid local IPv4 address. Rerun with --local-ip IPV4"

  if [[ -z "$PAQET_ROUTER_MAC" ]]; then
    GATEWAY_IP="$(get_gateway_ip "$PAQET_INTERFACE" || true)"
    [[ -n "$GATEWAY_IP" ]] || die "Could not detect the IPv4 gateway. Rerun with --router-mac MAC"
    if command -v ping >/dev/null 2>&1; then
      ping -c 1 -W 1 "$GATEWAY_IP" >/dev/null 2>&1 || true
    fi
    PAQET_ROUTER_MAC="$(get_neighbor_mac "$PAQET_INTERFACE" "$GATEWAY_IP" || true)"
  fi
  validate_mac "$PAQET_ROUTER_MAC" || die "Could not detect a valid gateway MAC. Rerun with --router-mac aa:bb:cc:dd:ee:ff"
  PAQET_ROUTER_MAC="${PAQET_ROUTER_MAC,,}"

  log_success "Interface ${PAQET_INTERFACE}, local IP ${PAQET_LOCAL_IP}, gateway MAC ${PAQET_ROUTER_MAC}"
fi

step "Creating or preserving the server configuration"

install -d -m 0750 -o root -g root "$CONFIG_DIR" "$LIB_DIR"

if [[ "$PRESERVE_EXISTING_CONFIG" == "1" ]]; then
  CONFIG_PORT="$(extract_config_port "$CONFIG_PATH")"
  [[ -n "$CONFIG_PORT" ]] || die "Existing config is preserved but its listen port could not be parsed: ${CONFIG_PATH}"
  validate_port "$CONFIG_PORT"
  CONFIG_KEY="$(extract_config_key "$CONFIG_PATH")"
  log_info "Preserving existing configuration: ${CONFIG_PATH}"
else
  if [[ -f "$CONFIG_PATH" ]]; then
    BACKUP_PATH="${CONFIG_PATH}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
    cp -a "$CONFIG_PATH" "$BACKUP_PATH"
    log_warn "Existing configuration backed up to ${BACKUP_PATH}"
  fi

  CONFIG_PORT="$PAQET_PORT"
  if [[ -z "$PAQET_KEY" ]]; then
    PAQET_KEY="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
  fi
  validate_key "$PAQET_KEY" || die "Generated or supplied key is invalid"
  CONFIG_KEY="$PAQET_KEY"

  CONFIG_TMP="${TMP_DIR}/server.yaml"
  cat > "$CONFIG_TMP" <<CONFIG
role: "server"

log:
  level: "info"

listen:
  addr: ":${CONFIG_PORT}"

network:
  interface: "${PAQET_INTERFACE}"
  ipv4:
    addr: "${PAQET_LOCAL_IP}:${CONFIG_PORT}"
    router_mac: "${PAQET_ROUTER_MAC}"
  tcp:
    local_flag: ["PA"]

transport:
  protocol: "kcp"
  conn: 1
  kcp:
    mode: "fast"
    block: "aes"
    key: "${CONFIG_KEY}"
CONFIG

  install -m 0600 -o root -g root "$CONFIG_TMP" "$CONFIG_PATH"
  log_success "Created ${CONFIG_PATH}"
fi

printf 'PAQET_PORT=%s\n' "$CONFIG_PORT" > "$FIREWALL_ENV"
chmod 0600 "$FIREWALL_ENV"

step "Installing idempotent firewall and systemd services"

install -d -m 0755 "$(dirname "$SERVICE_PATH")"

cat > "$FIREWALL_SCRIPT" <<'FIREWALL'
#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

readonly ENV_FILE="/etc/paqet-x/firewall.env"
readonly STATE_FILE="/run/paqet-x-firewall.port"

[[ -r "$ENV_FILE" ]] || { echo "Missing $ENV_FILE" >&2; exit 1; }
# ENV_FILE is root-owned and contains only PAQET_PORT=<integer>.
# shellcheck source=/dev/null
source "$ENV_FILE"
[[ "${PAQET_PORT:-}" =~ ^[0-9]+$ ]] || { echo "Invalid PAQET_PORT" >&2; exit 1; }

add_rule() {
  local table="$1"
  shift
  if ! iptables -w 5 -t "$table" -C "$@" >/dev/null 2>&1; then
    iptables -w 5 -t "$table" -I "$@"
  fi
}

remove_rule() {
  local table="$1"
  shift
  while iptables -w 5 -t "$table" -C "$@" >/dev/null 2>&1; do
    iptables -w 5 -t "$table" -D "$@"
  done
}

remove_for_port() {
  local port="$1"
  [[ "$port" =~ ^[0-9]+$ ]] || return 0
  remove_rule raw PREROUTING -p tcp --dport "$port" -j NOTRACK
  remove_rule raw OUTPUT -p tcp --sport "$port" -j NOTRACK
  remove_rule mangle OUTPUT -p tcp --sport "$port" --tcp-flags RST RST -j DROP
}

case "${1:-}" in
  start)
    mkdir -p "$(dirname "$STATE_FILE")"
    if [[ -r "$STATE_FILE" ]]; then
      old_port="$(cat "$STATE_FILE")"
      if [[ "$old_port" != "$PAQET_PORT" ]]; then
        remove_for_port "$old_port"
      fi
    fi
    add_rule raw PREROUTING -p tcp --dport "$PAQET_PORT" -j NOTRACK
    add_rule raw OUTPUT -p tcp --sport "$PAQET_PORT" -j NOTRACK
    add_rule mangle OUTPUT -p tcp --sport "$PAQET_PORT" --tcp-flags RST RST -j DROP
    printf '%s\n' "$PAQET_PORT" > "$STATE_FILE"
    ;;
  stop)
    port="$PAQET_PORT"
    [[ -r "$STATE_FILE" ]] && port="$(cat "$STATE_FILE")"
    remove_for_port "$port"
    rm -f "$STATE_FILE"
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 2
    ;;
esac
FIREWALL
chmod 0750 "$FIREWALL_SCRIPT"
chown root:root "$FIREWALL_SCRIPT"

cat > "$FIREWALL_SERVICE_PATH" <<UNIT
[Unit]
Description=Paqet X firewall rules
After=local-fs.target
Before=${SERVICE_NAME}

[Service]
Type=oneshot
ExecStart=${FIREWALL_SCRIPT} start
ExecStop=${FIREWALL_SCRIPT} stop
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT

cat > "$SERVICE_PATH" <<UNIT
[Unit]
Description=Paqet X raw-packet server
Documentation=https://github.com/${REPOSITORY}
After=network-online.target ${FIREWALL_SERVICE_NAME}
Wants=network-online.target
Requires=${FIREWALL_SERVICE_NAME}

[Service]
Type=simple
ExecStart=${BIN_PATH} run -c ${CONFIG_PATH}
Restart=on-failure
RestartSec=3s
TimeoutStopSec=15s
LimitNOFILE=1048576
UMask=0077
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=full
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
LockPersonality=yes
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW

[Install]
WantedBy=multi-user.target
UNIT

chmod 0644 "$SERVICE_PATH" "$FIREWALL_SERVICE_PATH"
chown root:root "$SERVICE_PATH" "$FIREWALL_SERVICE_PATH"
systemctl daemon-reload

if command -v systemd-analyze >/dev/null 2>&1; then
  if ! systemd-analyze verify "$SERVICE_PATH" "$FIREWALL_SERVICE_PATH" >/dev/null 2>&1; then
    log_warn "systemd-analyze reported a unit warning; installation will continue and startup will be checked"
  fi
fi

log_success "Installed systemd units and persistent idempotent firewall rules"

step "Starting and validating Paqet X"

if [[ "$SKIP_START" == "1" ]]; then
  log_warn "Services were installed but not started (--no-start)"
else
  systemctl enable "$FIREWALL_SERVICE_NAME" "$SERVICE_NAME" >/dev/null
  systemctl restart "$FIREWALL_SERVICE_NAME"
  systemctl restart "$SERVICE_NAME"
  sleep 2

  if ! systemctl is-active --quiet "$FIREWALL_SERVICE_NAME"; then
    journalctl -u "$FIREWALL_SERVICE_NAME" -n 30 --no-pager >&2 || true
    die "Firewall service did not start"
  fi

  if ! systemctl is-active --quiet "$SERVICE_NAME"; then
    journalctl -u "$SERVICE_NAME" -n 40 --no-pager >&2 || true
    die "Paqet X service did not start"
  fi

  log_success "Paqet X and firewall services are active"
fi

printf '\n%sInstallation complete%s\n' "$GREEN$BOLD" "$RESET"
printf '  Version:       %s\n' "$RELEASE_TAG"
printf '  Binary:        %s\n' "$BIN_PATH"
printf '  Configuration: %s\n' "$CONFIG_PATH"
printf '  Interface:     %s\n' "$PAQET_INTERFACE"
printf '  Local address: %s:%s\n' "$PAQET_LOCAL_IP" "$CONFIG_PORT"
printf '  Service:       %s\n' "$SERVICE_NAME"
if [[ -n "${CONFIG_KEY:-}" ]]; then
  printf '  Shared key:    %s\n' "$CONFIG_KEY"
else
  printf '  Shared key:    stored in %s\n' "$CONFIG_PATH"
fi
printf '\nUseful commands:\n'
printf '  systemctl status %s --no-pager\n' "$SERVICE_NAME"
printf '  journalctl -u %s -f\n' "$SERVICE_NAME"
printf '  %s version\n' "$BIN_PATH"
printf '\nYour cloud provider firewall/security group must allow inbound TCP port %s.\n' "$CONFIG_PORT"
printf 'Keep the shared key private and use the same Paqet release on clients.\n'
